---

- name: Check if nvm is installed
  stat: path={{ nvm_dir }}
  register: nvm_installed

- name: Clone nvm
  git: repo=https://github.com/creationix/nvm.git dest={{ nvm_dir }} accept_hostkey=true
  when: nvm_installed.stat.exists == false

- name: Checkout latest version
  shell: cd {{ nvm_dir }} && git checkout `git describe --abbrev=0 --tags`

- name: Update zshrc to load nvm
  lineinfile:
     dest={{ home_dir }}/.zshrc
     line=". ~/.nvm/nvm.sh"
     state=present
     insertafter=EOF

- name: Activate nvm and install latest stable node version
  shell: . {{ nvm_dir }}/nvm.sh && nvm install node && nvm use node && nvm alias default node executable=/bin/zsh

- name: Activate nvm and use latest stable node version
  shell: . {{ nvm_dir }}/nvm.sh && nvm use node executable=/bin/zsh

- name: Install npm packages
  npm: name={{ item }} global=yes
  with_items: npm_modules
  environment:
    PATH: "{{ ansible_env.PATH }}"
