---

- name: Check if ruby is installed
  stat: path={{ home_dir}}/.rbenv/versions/{{ ruby_version }}
  register: ruby_installed

- name: Install ruby
  shell: rbenv install {{ ruby_version }}
  when: ruby_installed.stat.exists == false

- name: Set latest ruby version as default
  shell: rbenv global {{ ruby_version }}

- name: Update system installed gems
  shell: gem update --system
  sudo: yes

- name: Install gems plugins
  gem: name={{ item }} state=latest
  sudo: yes
  with_items: ruby_gems
