---

- name: Check if oh-my-zsh is installed
  stat: path={{ home_dir}}/.oh-my-zsh
  register: oh_my_zsh_installed

- name: Clone oh-my-zsh repo
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest={{ home_dir }}/.oh-my-zsh accept_hostkey=true
  when: oh_my_zsh_installed.stat.exists == false

- name: Check if .zshrc is present
  stat: path={{ home_dir}}/.zshrc
  register: zshrc_present

- name: Create a new zsh configuration file
  shell: cp {{ home_dir }}/.oh-my-zsh/templates/zshrc.zsh-template {{ home_dir }}/.zshrc
  when: zshrc_present.stat.exists == false

- name: Check if zsh-syntax-highlighting is installed
  stat: path={{ home_dir}}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  register: zsh_syntax_highlighting_installed

- name: Install zsh-syntax-highlighting plugin
  git: repo=git://github.com/zsh-users/zsh-syntax-highlighting.git dest={{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting accept_hostkey=true
  when: zsh_syntax_highlighting_installed.stat.exists == false
